model:
  num_init_features: 32
  num_layers: 3
  block_depth: 3
  growth_rate: 4
  drop_rate: 0.2
  kernel_size: 3
  conv_mode: "full"

data:
  path: "data/"
  image_size: [384, 512]
  in_channels: 3
  out_channels: 3
  
train:
  epochs: 200
  batch_size: 16
  warmup_epochs: 3
  weight_decay: 0.01
  lr: 0.001
  lr_decay: 0.1
  lr_step: 1
  lr_scheduler: "poly"
  clip_grad: 1.0
  transforms:
    - ToTensor: null
    - Normalize:
        mean: 0.5
        std: 0.5


