model:
  in_channels: 3
  out_channels: 3
  num_init_features: 32
  num_layers: 3
  block_depth: 3
  growth_rate: 7
  exp_factor: 2
  drop_rate: 0.2
  kernel_size: 3
  conv_mode: "full"


train:
  epochs: 200
  batch_size: 3
  num_workers: 0
  warmup_epochs: 3
  weight_decay: 0.01
  lr: 0.001
  lr_gamma: 0.1
  lr_step: 1
  lr_power: 1.0
  lr_scheduler: "poly"
  clip_grad: null
  loss_fn: "JaccardLoss"
  transforms:
    - Resize:
        height: 290
        width: 512
        always_apply: True
    - HorizontalFlip:
        p: 0.3
    - RandomRotate90:
        p: 0.3
    - GaussianBlur:
        blur_limit: [5, 5]
        sigma_limit: [1.0, 1.0]
        p: 1.0
        always_apply: True
    - Normalize:
        mean: [0.0, 0.0, 0.0]
        std: [1.0, 1.0, 1.0]
        always_apply: True

eval:
  batch_size: 3
  num_workers: 0
  transforms:
    - Resize:
        height: 290
        width: 512
        always_apply: True
    - GaussianBlur:
        blur_limit: [5, 5]
        sigma_limit: [1.0, 1.0]
        p: 1.0
        always_apply: True
    - Normalize:
        mean: [0.0, 0.0, 0.0]
        std: [1.0, 1.0, 1.0]
        always_apply: True