from yacs.config import CfgNode

_C = CfgNode()

_C.DATA = CfgNode()
_C.DATA.IMAGE_SIZE = 256
_C.DATA.IN_CHANNELS = 2
_C.DATA.OUT_CHANNELS = 2

_C.MODEL = CfgNode()
_C.MODEL.EXP_FACTOR = 2
_C.MODEL.NUM_LAYERS = 4
_C.MODEL.NUM_RESIDUALS = 2
_C.MODEL.KERNEL_SIZE = 3
_C.MODEL.STRIDE = 2
_C.MODEL.EMBED_DIM = 16
_C.MODEL.UP_MODE = 'bilinear'
_C.MODEL.DOWN_MODE = 'conv'
_C.MODEL.CONV_MODE = 'full'
_C.MODEL.SKIP_TYPE = 'cat'

_C.TRAIN = CfgNode()
_C.TRAIN.EPOCHS = 200
_C.TRAIN.WARMUP_EPOCHS = 3
_C.TRAIN.WEIGHT_DECAY = 1e-2
_C.TRAIN.LR = 1e-3
_C.TRAIN.LR_DECAY = 0.1
_C.TRAIN.LR_STEP = 1
_C.TRAIN.LR_SCHEDULER = 'poly'
_C.TRAIN.CLIP_GRAD = 1.0